- name: Update and upgrade apt packages (only on first host)
  apt:
    update_cache: yes
    upgrade: dist
  when: inventory_hostname == ansible_play_hosts_all[0]
  tags: apt_upgrade

- name: Install required packages
  apt:
    name:
      - git
      - curl
      - build-essential
    state: present

- name: Ensure taskboard directory exists
  file:
    path: /home/{{ ansible_user }}/taskboard
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Create environment file
  template:
    src: .env.j2
    dest: /home/{{ ansible_user }}/taskboard/.env
    mode: '0644'