---
- name: Install Node.js
  shell: curl -sL https://deb.nodesource.com/setup_22.x | bash -
  become: yes

- name: Install Node.js and npm
  apt:
    name: 
      - nodejs
    state: present
  become: yes

- name: Create .env file for Node.js
  copy:
    dest: /home/ubuntu/.env
    content: |
      DB_HOST={{ hostvars[groups['postgres'][0]].ansible_host }}
      DB_USER=postgres
      DB_PASSWORD=example
      DB_NAME=taskboard
    owner: ubuntu
    group: ubuntu
    mode: '0644'